<?php

/**
 * @file
 * Contains uis_custom_blocks.module.
 */



/**
 * Implements hook_gutenberg_blocks().
 */
// Basic Card example, you need to add in all the attributes for a card line by line
// uis-custom-blocks always stays the same but after the slash you put the name of the card you are adding
function uis_custom_blocks_gutenberg_blocks() {
  return [
    'uis-custom-blocks/my-custom-block' => [
      'attributes' => [
        'content' => [
          'type' => 'string',
        ],
      ],
      'category' => 'common',
    ],

//uis-card block registration    
    'uis-custom-blocks/uis-card' => [
      'attributes' => [
        'headerText' => [
          'type' => 'string',
        ],
        'title' => [
          'type' => 'string',
        ],
        'content' => [
          'type' => 'string',
        ],
        'linkUrl' => [
          'type' => 'string',
        ],
      ],
      'category' => 'common',
    ],
  
  //Registration for uis card container
  'uis-custom-blocks/uis-card-container' => [
  ],

//Registraion for image card container 
   'uis-custom-blocks/image-card-container' => [
  ],
  
  // Registration for uis-image-card block
  'uis-custom-blocks/uis-image-card' => [
    'attributes' => [
      'linkUrl' => [
        'type' => 'string',
      ],
      'imageUrl' => [
        'type' => 'string',
      ],
      'title' => [
        'type' => 'string',
      ],
    ],
    'category' => 'common',
  ],
  
// Advanced accordion (container) registration
'uis-custom-blocks/advanced-accordian' => [
  'attributes' => [
    'title' => [
      'type' => 'string',
    ],
  ],
  'category' => 'common',
],




//ADD NEW BLOCKS HERE AS NEEDED
  ];
}














// Should never need to touch these
/**
 * Implements hook_library_info_alter().
 */
function uis_custom_blocks_library_info_alter(&$libraries, $extension) {
  if ($extension === 'gutenberg') {
    $libraries['editor']['dependencies'][] = 'uis_custom_blocks/uis_custom_blocks';
    // Add the editor styles library as a dependency to Gutenberg editor
    $libraries['editor']['dependencies'][] = 'uis_custom_blocks/uis_custom_blocks_editor';
  }
}

/**
 * Implements hook_gutenberg_editor_assets().
 */
function uis_custom_blocks_gutenberg_editor_assets() {
  return [
    'uis_custom_blocks/uis_custom_blocks',
    'uis_custom_blocks/uis_custom_blocks_editor',
  ];
}

/**
 * Implements hook_page_attachments().
 */
function uis_custom_blocks_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'uis_custom_blocks/uis_custom_blocks';
}

