<?php

/**
 * @file
 * Contains uis_custom_blocks.module.
 */

/**
 * Implements hook_gutenberg_blocks().
 */
function uis_custom_blocks_gutenberg_blocks() {
  return [
    'uis-custom-blocks/my-custom-block' => [
      'attributes' => [
        'content' => [
          'type' => 'string',
        ],
      ],
      'category' => 'common',
    ],

    // uis-custom-blocks always stays the same but after the slash you put the name of the card you are adding
    'uis-custom-blocks/uis-card' => [
      "attributes" => [
        'headerText' => [
          'type' => 'string',
        ],
        'title' => [
          'type' => 'string',
        ],
        'content' => [
          'type' => 'string',
        ],
        'linkUrl' => [
          'type' => 'string',
        ],
      ],
      'category' => 'common',
    ],
  ];
}

// Should never need to touch these
/**
 * Implements hook_library_info_alter().
 */
function uis_custom_blocks_library_info_alter(&$libraries, $extension) {
  if ($extension === 'gutenberg') {
    $libraries['editor']['dependencies'][] = 'uis_custom_blocks/uis_custom_blocks';
    // Add the editor styles library as a dependency to Gutenberg editor
    $libraries['editor']['dependencies'][] = 'uis_custom_blocks/uis_custom_blocks_editor';
  }
}

/**
 * Implements hook_gutenberg_editor_assets().
 */
function uis_custom_blocks_gutenberg_editor_assets() {
  return [
    'uis_custom_blocks/uis_custom_blocks',
    'uis_custom_blocks/uis_custom_blocks_editor',
  ];
}

/**
 * Implements hook_page_attachments().
 */
function uis_custom_blocks_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'uis_custom_blocks/uis_custom_blocks';
}

